version: "3.9"
services:

  postgres:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    user: '$UID:$GID'
    env_file:
      - .env
    volumes:
      - ./docker/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    depends_on:
      - postgres
    networks:
      - postgres

volumes:
  pg_data:
  pgadmin_data:


networks:
  postgres:
    driver: bridge
