import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Менеджер задач",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" data-theme="cupcake">
      <body className={`w-1/2 p-4 mx-auto ${inter.className}`}>
        <header className="my-4 w-full flex items-center justify-center">
          <Link href={"/issues"} className="btn btn-ghost text-2xl">
            Задачи
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
